# Verion of docker-compose to use 
version: "3"

services:
  app: # This is the service for the Django application
    build:
      context: . # Sets the directory containing a Dockerfile .

    # Maps port on the local machine to port on Docker image
    ports:
      - "8080:8080"
      
    volumes: 
    # Copy changes made to the project to your image working directory as changesare made.
      - .:/django-docker-okteto
    # Handles the command used to run the project in the Docker container.  
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    
    environment:
      # The environment variable credetials that is needed 
      # in django settings for Postgres to work.
      - DB_HOST=db
      - DB_NAME=database-name
      - DB_USER=postgres-user1
      - DB_PASS=nvjfeifejijmf2424
    depends_on:
      - db

  db:
    image: postgres:10-alpine # pulling Postgress image from Docker hub
    environment:
      # credentials required by postgres image
      - POSTGRES_DB=database-name
      - POSTGRES_USER=postgres-user1
      - POSTGRES_PASSWORD=nvjfeifejijmf2424